# Generated by Django 5.2.5 on 2026-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signupotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image_url',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
    ]
