# Generated by Django 5.2.5 on 2026-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Additional notes about delivery status or updates'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_estimate',
            field=models.CharField(blank=True, help_text="Estimated delivery time (e.g., '15 mins to reach', '30-45 mins')", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('at_service', 'At Service'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
